# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
